name: 🐛 Bug
description: Report an issue to help improve the project.
labels: bug
body:
  - type: textarea
    attributes:
      label: Description*
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?