name: 💡 General Feature Request
description: Suggest features, propose improvements, discuss new ideas!
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Description*
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?