import Link from "next/link"

export const metadata = {
  title: "Terms of Service - Gems Of India",
  description:
    "Read the Terms of Service governing the use of the Gems Of India platform, its services, and user-contributed content.",
}

export default function TermsOfServicePage() {
  const lastUpdatedDate = "August 20, 2025" // It's better to set a static date for legal documents.

  return (
    <div className="bg-secondary/20 py-8 sm:py-12">
      <div className="prose prose-zinc dark:prose-invert container mx-auto max-w-4xl px-4">
        <div className="bg-background rounded-xl border p-6 shadow-sm sm:p-8 dark:border-zinc-800">
          <h1 className="mb-2 text-2xl font-bold sm:text-3xl">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last Updated: {lastUpdatedDate}</p>

          <div className="text-foreground/80 space-y-6 text-sm sm:text-base">
            <p>
              Welcome to Gems Of India (&quot;the Platform&quot;). These Terms of Service
              (&quot;Terms&quot;) govern your access to and use of our website, services, and
              platform (collectively, &quot;Services&quot;). Please read these Terms carefully
              before using our Services.
            </p>
            <p>
              By accessing or using our Services, you agree to be bound by these Terms. If you do
              not agree to these Terms, you may not access or use the Services.
            </p>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              1. Description of Service
            </h2>
            <p>
              Gems Of India is a public, community-driven platform that allows users to rate,
              review, and discuss government departments, public officials, and government
              infrastructure. The content on the platform is primarily generated by users.
            </p>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              2. User-Generated Content
            </h2>
            <p>
              You are solely responsible for any content you post, upload, or otherwise contribute
              to the platform, including ratings, reviews, comments, and information (&quot;User
              Content&quot;).
            </p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong>License:</strong> By submitting User Content, you grant Gems Of India a
                worldwide, non-exclusive, royalty-free, perpetual license to use, reproduce,
                distribute, display, and perform your content in connection with the Services.
              </li>
              <li>
                <strong>Responsibility:</strong> You affirm that your User Content is accurate to
                the best of your knowledge, does not violate any laws, and does not infringe on the
                rights of any third party.
              </li>
              <li>
                <strong>Prohibited Content:</strong> You may not post content that is defamatory,
                harassing, threatening, hateful, invasive of another&apos;s privacy, illegal, or
                that contains verifiable misinformation. Publishing private, non-public information
                about individuals is strictly prohibited.
              </li>
            </ul>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              3. Platform&apos;s Role and Disclaimers
            </h2>
            <p>
              Gems Of India is a neutral platform for the distribution of user-generated
              information.
            </p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong>No Endorsement:</strong> We do not endorse, support, represent, or guarantee
                the completeness, truthfulness, accuracy, or reliability of any User Content posted
                on the Services.
              </li>
              <li>
                <strong>No Verification:</strong> We do not verify the identity of users or the
                validity of the information they post. All content is provided &quot;as is&quot;.
                Your reliance on any information found on the platform is solely at your own risk.
              </li>
              <li>
                <strong>Right to Moderate:</strong> We reserve the right, but not the obligation, to
                remove or refuse to distribute any User Content that violates these Terms or our
                Community Guidelines.
              </li>
            </ul>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              4. Acceptable Use
            </h2>
            <p>You agree not to use the Services to:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Engage in any activity that is illegal or fraudulent.</li>
              <li>Impersonate any person or entity.</li>
              <li>Harass, abuse, or harm another person.</li>
              <li>Interfere with or disrupt the operation of the Services.</li>
            </ul>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              5. Termination
            </h2>
            <p>
              We may suspend or terminate your account and access to the Services at our sole
              discretion, without prior notice, for conduct that we believe violates these Terms or
              is otherwise harmful to other users of the Services, us, or third parties.
            </p>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              6. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by applicable law, Gems Of India shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, or any loss
              of profits or revenues, whether incurred directly or indirectly, or any loss of data,
              use, goodwill, or other intangible losses, resulting from your use of the Services or
              any content posted on the platform.
            </p>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              7. Governing Law
            </h2>
            <p>
              These Terms shall be governed by the laws of [Your Jurisdiction, e.g., India or State
              of Texas, USA], without respect to its conflict of laws principles.
            </p>

            <h2 className="!mt-8 border-t pt-6 text-xl font-semibold dark:border-zinc-800">
              8. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify you of any
              changes by posting the new Terms on this page. Your continued use of the Service after
              any such change constitutes your acceptance of the new Terms.
            </p>
          </div>

          <div className="mt-8 border-t pt-6 dark:border-zinc-800">
            <Link href="/legal" className="text-primary hover:underline">
              &larr; Back to Legal Information
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
